aggregator:
  kafka:
    producer-props:
      bootstrap.servers: localhost:9092
      client.id: "aggregator-client"
      key.serializer: org.apache.kafka.common.serialization.LongSerializer
      value.serializer: ru.practicum.ewm.aggregator.stats.avro.AvroSerializer
    consumer-props:
      bootstrap.servers: localhost:9092
      group.id: "aggregator-group"
      key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value.deserializer: ru.practicum.ewm.aggregator.stats.avro.UserActionDeserializer
      enable.auto.commit: "false"
    user-actions-topic: stats.user-actions.v1
    events-similarity-topic: stats.events-similarity.v1