spring:
  datasource:
    url: jdbc:postgresql://localhost:4434/request
    username: request
    password: request
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: false

  logging:
    level:
      ru.practicum.ewm: DEBUG

grpc:
  client:
    collector:
      address: 'discovery:///collector'
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      use-tls: false