spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/stats
    username: stats
    password: stats
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true

  logging:
    level:
      ru.practicum: DEBUG

analyzer:
  kafka:
    user-action-consumer-props:
      bootstrap.servers: localhost:9092
      group.id: "analyzer-group"
      key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value.deserializer: ru.practicum.analyzer.stats.avro.UserActionDeserializer
      enable.auto.commit: "false"
      auto.offset.reset: "earliest"
    event-similarity-consumer-props:
      bootstrap.servers: localhost:9092
      group.id: "analyzer-group"
      key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value.deserializer: ru.practicum.analyzer.stats.avro.EventSimilarityDeserializer
      enable.auto.commit: "false"
      auto.offset.reset: "earliest"
    user-actions-topic: stats.user-actions.v1
    events-similarity-topic: stats.events-similarity.v1
